package org.fireply.entity;
// Generated 2016-5-16 23:27:45 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Qrcode generated by hbm2java
 */
public class Qrcode implements java.io.Serializable {

    private String id;
    private String info;
    private String imageSrc;
    private Set<User> users = new HashSet<User>(0);
    private Set<Proxy> proxies = new HashSet<Proxy>(0);

    public Qrcode() {
    }

    public Qrcode(String id, String info, String imageSrc) {
        this.id = id;
        this.info = info;
        this.imageSrc = imageSrc;
    }

    public Qrcode(String id, String info, String imageSrc, Set<User> users, Set<Proxy> proxies) {
        this.id = id;
        this.info = info;
        this.imageSrc = imageSrc;
        this.users = users;
        this.proxies = proxies;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getInfo() {
        return this.info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public String getImageSrc() {
        return this.imageSrc;
    }

    public void setImageSrc(String imageSrc) {
        this.imageSrc = imageSrc;
    }

    public Set<User> getUsers() {
        return this.users;
    }

    public void setUsers(Set<User> users) {
        this.users = users;
    }

    public Set<Proxy> getProxies() {
        return this.proxies;
    }

    public void setProxies(Set<Proxy> proxies) {
        this.proxies = proxies;
    }

}
