package org.fireply.enter.entity;
// Generated 2016-5-16 23:27:45 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Commit generated by hbm2java
 */
public class Commit implements java.io.Serializable {

    private String id;
    private News news;
    private User user;
    private String content;
    private Date createTime;

    public Commit() {
    }

    public Commit(String id, News news, String content, Date createTime) {
        this.id = id;
        this.news = news;
        this.content = content;
        this.createTime = createTime;
    }

    public Commit(String id, News news, User user, String content, Date createTime) {
        this.id = id;
        this.news = news;
        this.user = user;
        this.content = content;
        this.createTime = createTime;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public News getNews() {
        return this.news;
    }

    public void setNews(News news) {
        this.news = news;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

}
