package org.fireply.enter.entity;
// Generated 2016-5-19 7:55:16 by Hibernate Tools 4.3.1.Final

/**
 * ProductionGallery generated by hbm2java
 */
public class ProductionGallery implements java.io.Serializable {

    private String id;
    private Production production;
    private String imageSrc;

    public ProductionGallery() {
    }

    public ProductionGallery(String id, Production production, String imageSrc) {
        this.id = id;
        this.production = production;
        this.imageSrc = imageSrc;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Production getProduction() {
        return this.production;
    }

    public void setProduction(Production production) {
        this.production = production;
    }

    public String getImageSrc() {
        return this.imageSrc;
    }

    public void setImageSrc(String imageSrc) {
        this.imageSrc = imageSrc;
    }

}
