package org.fireply.enter.entity;
// Generated 2016-5-16 23:27:45 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Production generated by hbm2java
 */
public class Production implements java.io.Serializable {

    private String id;
    private Category category;
    private String name;
    private String price;
    private String desc;
    private String thumb;
    private Set<ProductionGallery> productionGalleries = new HashSet<ProductionGallery>(0);
    private Set<Order> orders = new HashSet<Order>(0);

    public Production() {
    }

    public Production(String id, String name, String price, String thumb) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.thumb = thumb;
    }

    public Production(String id, Category category, String name, String price, String desc, String thumb,
            Set<ProductionGallery> productionGalleries, Set<Order> orders) {
        this.id = id;
        this.category = category;
        this.name = name;
        this.price = price;
        this.desc = desc;
        this.thumb = thumb;
        this.productionGalleries = productionGalleries;
        this.orders = orders;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Category getCategory() {
        return this.category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPrice() {
        return this.price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getThumb() {
        return this.thumb;
    }

    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    public Set<ProductionGallery> getProductionGalleries() {
        return this.productionGalleries;
    }

    public void setProductionGalleries(Set<ProductionGallery> productionGalleries) {
        this.productionGalleries = productionGalleries;
    }

    public Set<Order> getOrders() {
        return this.orders;
    }

    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }

}
