package org.fireply.enter.entity;
// Generated 2016-5-19 7:55:16 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Proxy generated by hbm2java
 */
public class Proxy implements java.io.Serializable {

    private String id;
    private Qrcode qrcode;
    private User user;
    private String name;
    private boolean level;
    private String phone;
    private String address;
    private String proxyDesc;
    private Set<Order> orders = new HashSet<Order>(0);

    public Proxy() {
    }

    public Proxy(String id, User user, String name, boolean level, String phone, String address) {
        this.id = id;
        this.user = user;
        this.name = name;
        this.level = level;
        this.phone = phone;
        this.address = address;
    }

    public Proxy(String id, Qrcode qrcode, User user, String name, boolean level, String phone, String address,
            String proxyDesc, Set<Order> orders) {
        this.id = id;
        this.qrcode = qrcode;
        this.user = user;
        this.name = name;
        this.level = level;
        this.phone = phone;
        this.address = address;
        this.proxyDesc = proxyDesc;
        this.orders = orders;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Qrcode getQrcode() {
        return this.qrcode;
    }

    public void setQrcode(Qrcode qrcode) {
        this.qrcode = qrcode;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isLevel() {
        return this.level;
    }

    public void setLevel(boolean level) {
        this.level = level;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getProxyDesc() {
        return this.proxyDesc;
    }

    public void setProxyDesc(String proxyDesc) {
        this.proxyDesc = proxyDesc;
    }

    public Set<Order> getOrders() {
        return this.orders;
    }

    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }

}
