package org.fireply.enter.entity;
// Generated 2016-5-19 7:55:16 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private String id;
    private Account account;
    private Qrcode qrcode;
    private String password;
    private String name;
    private Boolean sex;
    private String nativePlace;
    private String birthday;
    private String mobile;
    private String email;
    private String userDesc;
    private String headThumb;
    private Set<News> newses = new HashSet<News>(0);
    private Set<Proxy> proxies = new HashSet<Proxy>(0);
    private Set<Order> orders = new HashSet<Order>(0);
    private Set<Commit> commits = new HashSet<Commit>(0);

    public User() {
    }

    public User(String id) {
        this.id = id;
    }

    public User(String id, Account account, Qrcode qrcode, String password, String name, Boolean sex,
            String nativePlace, String birthday, String mobile, String email, String userDesc, String headThumb,
            Set<News> newses, Set<Proxy> proxies, Set<Order> orders, Set<Commit> commits) {
        this.id = id;
        this.account = account;
        this.qrcode = qrcode;
        this.password = password;
        this.name = name;
        this.sex = sex;
        this.nativePlace = nativePlace;
        this.birthday = birthday;
        this.mobile = mobile;
        this.email = email;
        this.userDesc = userDesc;
        this.headThumb = headThumb;
        this.newses = newses;
        this.proxies = proxies;
        this.orders = orders;
        this.commits = commits;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Account getAccount() {
        return this.account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    public Qrcode getQrcode() {
        return this.qrcode;
    }

    public void setQrcode(Qrcode qrcode) {
        this.qrcode = qrcode;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getSex() {
        return this.sex;
    }

    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    public String getNativePlace() {
        return this.nativePlace;
    }

    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace;
    }

    public String getBirthday() {
        return this.birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUserDesc() {
        return this.userDesc;
    }

    public void setUserDesc(String userDesc) {
        this.userDesc = userDesc;
    }

    public String getHeadThumb() {
        return this.headThumb;
    }

    public void setHeadThumb(String headThumb) {
        this.headThumb = headThumb;
    }

    public Set<News> getNewses() {
        return this.newses;
    }

    public void setNewses(Set<News> newses) {
        this.newses = newses;
    }

    public Set<Proxy> getProxies() {
        return this.proxies;
    }

    public void setProxies(Set<Proxy> proxies) {
        this.proxies = proxies;
    }

    public Set<Order> getOrders() {
        return this.orders;
    }

    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }

    public Set<Commit> getCommits() {
        return this.commits;
    }

    public void setCommits(Set<Commit> commits) {
        this.commits = commits;
    }

}
