package org.fireply.enter.model;
// Generated 2016-5-26 6:45:30 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

    private String id;
    private User user;
    private String password;
    private Set<AdminAuthorization> adminAuthorizations = new HashSet<AdminAuthorization>(0);

    public Admin() {
    }

    public Admin(String id, User user, String password) {
        this.id = id;
        this.user = user;
        this.password = password;
    }

    public Admin(String id, User user, String password, Set<AdminAuthorization> adminAuthorizations) {
        this.id = id;
        this.user = user;
        this.password = password;
        this.adminAuthorizations = adminAuthorizations;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Set<AdminAuthorization> getAdminAuthorizations() {
        return this.adminAuthorizations;
    }

    public void setAdminAuthorizations(Set<AdminAuthorization> adminAuthorizations) {
        this.adminAuthorizations = adminAuthorizations;
    }

}
