package org.fireply.enter.model;
// Generated 2016-5-26 6:45:30 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * AdminAuthorization generated by hbm2java
 */
public class AdminAuthorization implements java.io.Serializable {

    private Integer id;
    private Admin admin;
    private String sequence;
    private String token;
    private Date lastTime;

    public AdminAuthorization() {
    }

    public AdminAuthorization(Admin admin, String sequence, String token, Date lastTime) {
        this.admin = admin;
        this.sequence = sequence;
        this.token = token;
        this.lastTime = lastTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Admin getAdmin() {
        return this.admin;
    }

    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

    public String getSequence() {
        return this.sequence;
    }

    public void setSequence(String sequence) {
        this.sequence = sequence;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public Date getLastTime() {
        return this.lastTime;
    }

    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

}
