package org.fireply.enter.model;
// Generated 2016-5-23 16:15:06 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Authorization generated by hbm2java
 */
public class Authorization implements java.io.Serializable {

    private Integer id;
    private User user;
    private String sequence;
    private String token;
    private Date lastTime;

    public Authorization() {
    }

    public Authorization(User user, String sequence, String token, Date lastTime) {
        this.user = user;
        this.sequence = sequence;
        this.token = token;
        this.lastTime = lastTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getSequence() {
        return this.sequence;
    }

    public void setSequence(String sequence) {
        this.sequence = sequence;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public Date getLastTime() {
        return this.lastTime;
    }

    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

}
