package org.fireply.enter.model;
// Generated 2016-5-23 16:15:06 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Login generated by hbm2java
 */
public class Login implements java.io.Serializable {

    private Integer id;
    private User user;
    private int ip;
    private Date lastTime;
    private Short passwordSuccess;
    private Short passwordFailure;
    private Short cookieSuccess;
    private Short sequenceFailure;
    private Short multiDeviceFactor;
    private Short ipFactor;

    public Login() {
    }

    public Login(User user, int ip, Date lastTime) {
        this.user = user;
        this.ip = ip;
        this.lastTime = lastTime;
    }

    public Login(User user, int ip, Date lastTime, Short passwordSuccess, Short passwordFailure, Short cookieSuccess,
            Short sequenceFailure, Short multiDeviceFactor, Short ipFactor) {
        this.user = user;
        this.ip = ip;
        this.lastTime = lastTime;
        this.passwordSuccess = passwordSuccess;
        this.passwordFailure = passwordFailure;
        this.cookieSuccess = cookieSuccess;
        this.sequenceFailure = sequenceFailure;
        this.multiDeviceFactor = multiDeviceFactor;
        this.ipFactor = ipFactor;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public int getIp() {
        return this.ip;
    }

    public void setIp(int ip) {
        this.ip = ip;
    }

    public Date getLastTime() {
        return this.lastTime;
    }

    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    public Short getPasswordSuccess() {
        return this.passwordSuccess;
    }

    public void setPasswordSuccess(Short passwordSuccess) {
        this.passwordSuccess = passwordSuccess;
    }

    public Short getPasswordFailure() {
        return this.passwordFailure;
    }

    public void setPasswordFailure(Short passwordFailure) {
        this.passwordFailure = passwordFailure;
    }

    public Short getCookieSuccess() {
        return this.cookieSuccess;
    }

    public void setCookieSuccess(Short cookieSuccess) {
        this.cookieSuccess = cookieSuccess;
    }

    public Short getSequenceFailure() {
        return this.sequenceFailure;
    }

    public void setSequenceFailure(Short sequenceFailure) {
        this.sequenceFailure = sequenceFailure;
    }

    public Short getMultiDeviceFactor() {
        return this.multiDeviceFactor;
    }

    public void setMultiDeviceFactor(Short multiDeviceFactor) {
        this.multiDeviceFactor = multiDeviceFactor;
    }

    public Short getIpFactor() {
        return this.ipFactor;
    }

    public void setIpFactor(Short ipFactor) {
        this.ipFactor = ipFactor;
    }

}
