package org.fireply.enter.model;
// Generated 2016-5-23 16:15:06 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

    private Integer id;
    private Production production;
    private Proxy proxy;
    private User user;
    private String price;
    private Date createTime;
    private String qrcodeId;

    public Order() {
    }

    public Order(String price, Date createTime) {
        this.price = price;
        this.createTime = createTime;
    }

    public Order(Production production, Proxy proxy, User user, String price, Date createTime, String qrcodeId) {
        this.production = production;
        this.proxy = proxy;
        this.user = user;
        this.price = price;
        this.createTime = createTime;
        this.qrcodeId = qrcodeId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Production getProduction() {
        return this.production;
    }

    public void setProduction(Production production) {
        this.production = production;
    }

    public Proxy getProxy() {
        return this.proxy;
    }

    public void setProxy(Proxy proxy) {
        this.proxy = proxy;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getPrice() {
        return this.price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getQrcodeId() {
        return this.qrcodeId;
    }

    public void setQrcodeId(String qrcodeId) {
        this.qrcodeId = qrcodeId;
    }

}
